### ISSUE TITLE
Cannot authenticate using query parameters

### ISSUE THREAD

**Issue by AlexKasaku** [contentstack/gatsby-source-contentstack#67] opened 2020-10-13 16:13 UTC
I've setup a new stack and tried the sample project with this plugin, but this results in this error:

```json
{
   "error_message":"Bad Request",
   "error_code":1,
   "errors":{
      "params":[
         "Using authentication parameters such as authtoken, api_key, access_token, and authorization as query parameters is prohibited."
      ]
   }
}
```

Looking at the [delivery API docs](https://www.contentstack.com/docs/developers/apis/content-delivery-api/#http-headers), the following is stated:

> For stacks that are part of organizations created after June 24, 2020:

> Users will not be able to use authentication parameters such as api_key (Stack API key), access_token (access token of the stack), authtoken (user generated authtoken), and authorization (management token of the stack) as query parameters for any stack-specific API requests.

Will this plugin be updated to pass these in as http headers? If not is there a workaround?

**Comment by cs-ecosystem-dev** [comment] 2020-10-13 16:23
@AlexKasaku Hello, sorry about the inconvenience caused. This looks like a random issue. To reproduce this issue at our end, we would like you to share some stack related details with us. You can reach me at vikram.kalta@contentstack.com.

**Comment by vkalta** [comment] 2020-10-13 16:24
@AlexKasaku Hello, sorry about the inconvenience caused. This looks like a random issue. To reproduce this issue at our end, we would like you to share some stack related details with us. You can reach me at vikram.kalta@contentstack.com.

**Comment by cs-ecosystem-dev** [comment] 2020-10-15 06:19
@AlexKasaku closing this issue, as this issue has been handled in the latest patch release.

Cheers!

**Comment by vkalta** [comment] 2020-10-15 06:20
@AlexKasaku closing this issue, as this issue has been handled in the latest patch release.

Cheers!

**Closed by vkalta** 2020-10-15 06:20 UTC
Labels: bug

**Comment by AlexKasaku** [comment] 2020-10-15 10:46
Thanks @vkalta , I was just about to create a PR this morning with the same fix but beat me to it!
