### ISSUE TITLE
When i configure multiple stacks  i get this error.

### ISSUE THREAD

**Issue by niranjanbala** [contentstack/gatsby-source-contentstack#56] opened 2020-09-08 17:31 UTC
ERROR #11321  PLUGIN

"gatsby-source-contentstack" threw an error while running the sourceNodes lifecycle:

Cannot read property 'schema' of undefined

**Comment by ninadhatkar** [comment] 2020-09-10 18:12
@niranjanbala Thanks for reporting this issue. We are able to reproduce and found the cause of it. We are working on getting this resolved, will keep you posted.

**Comment by vkalta** [comment] 2020-09-18 10:46
@niranjanbala closing this issue, as this scenario has been handled in the latest patch release.

Cheers!

**Closed by vkalta** 2020-09-18 10:46 UTC
